# Project information
site_name: 'Kobol Wiki'
site_description: 'Kobol Wiki'
site_author: 'Kobol Team'
site_url: 'https://wiki.kobol.io'

# Repository
repo_name: 'Kobol GitHub Repo'
repo_url: 'https://github.com/kobol-io'
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; Kobol Innovations Pte. Ltd. 2020'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  favicon: 'img/favicon.png'
  logo: 'img/kobol_logo.svg'
  icon:
    repo: 'fontawesome/brands/git-alt'
  custom_dir: 'theme'
  features:
    - tabs
  palette:
    primary: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - css/extra.css

# Options
extra:
  social:
    - icon: 'fontawesome/solid/home'
      link: 'https://kobol.io'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/kobol-io'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://facebook.com/kobol.io'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/kobol_io'
    - icon: 'fontawesome/solid/rss-square'
      link: 'https://blog.kobol.io'
  disqus: 'kobol-wiki'

# Google Analytics
google_analytics:
  - 'UA-96982596-2'
  - 'auto'

# Plugins
plugins:
  - search
  - git-revision-date-localized

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.tabbed
  - lightgallery

# Page naming
nav:
- Home: 'index.md'
- Helios64:
  - Introduction: 'helios64/intro.md'
  - Kit Assembly: 'helios64/kit.md'
  - Download: '/download/#helios64'
  - Install:
    - Preliminary : 'helios64/install/preliminary.md'
    - eMMC Install : 'helios64/install/emmc.md'
    - SDcard Install : 'helios64/install/sdcard.md'
    - First Start : 'helios64/install/first-start.md'
  - Recovery :
    - Recovery Mode: '/helios64/button/#recovery-button'
    - Maskrom Mode: 'helios64/maskrom.md'
  - Hardware:
    - Overview: 'helios64/hardware.md'
    - Button: 'helios64/button.md'
    - Ethernet: 'helios64/ethernet.md'
    - Front Panel: 'helios64/front-panel.md'
    - GPIO: 'helios64/gpio.md'
    - I2C: 'helios64/i2c.md'
    - Jumper: 'helios64/jumper.md'
    - LED: 'helios64/led.md'
    - M.2: 'helios64/m2.md'
    - Power Management:
      - PMIC: 'helios64/pmic.md'
      - Auto Power-On: 'helios64/auto_poweron.md'
      - UPS Battery: 'helios64/ups.md'
    - PWM Fan: 'helios64/pwm.md'
    - RTC: 'helios64/rtc.md'
    - SATA: 'helios64/sata.md'
    - SPI: 'helios64/spi.md'
    - UEXT: 'helios64/uext.md'
    - USB: 'helios64/usb.md'
  - Documents: 'helios64/docs.md'
  - Troubleshooting: 'helios64/troubleshoot.md'
- Helios4:
  - Introduction: 'helios4/intro.md'
  - Kit Assembly: 'helios4/kit.md'
  - Download: '/download/#helios4'
  - Install: 'helios4/install.md'
  - O/S:
    - Arch Linux: 'helios4/arch.md'
    - Armbian: 'helios4/armbian.md'
    - FreeBSD: 'helios4/freebsd.md'
    - Syncloud: 'helios4/syncloud.md'
    - U-Boot (bootloader): 'helios4/uboot.md'
  - Software:
    - Mdadm (RAID): 'helios4/mdadm.md'
    - NextCloud: 'helios4/nextcloud.md'
    - OpenMediaVault: 'helios4/omv.md'
  - Hardware:
    - Overview: 'helios4/hardware.md'
    - CESA (HW Crypto): 'helios4/cesa.md'
    - GPIO: 'helios4/gpio.md'
    - I2C (OLED): 'helios4/i2c.md'
    - LED: 'helios4/led.md'
    - PWM (Fan): 'helios4/pwm.md'
    - SDIO (SD Card): 'helios4/sdcard.md'
    - SPI (NOR Flash): 'helios4/spi.md'
    - Wake-on-LAN: 'helios4/wol.md'
  - Documents: 'helios4/docs.md'
- Download: 'download.md'
- About: 'about.md'
